"""empty message

Revision ID: 09bd3cd9189a
Revises: e150ec6634dd
Create Date: 2016-07-15 10:37:41.384000

"""

# revision identifiers, used by Alembic.
revision = '09bd3cd9189a'
down_revision = 'e150ec6634dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
