"""empty message

Revision ID: 09d17559af7f
Revises: dd7b06fbb74c
Create Date: 2016-07-20 10:15:46.769000

"""

# revision identifiers, used by Alembic.
revision = '09d17559af7f'
down_revision = 'dd7b06fbb74c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugs', sa.Column('bug_forbidden_status', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'bugs', ['bug_id'])
    op.drop_column('bugs', 'bug_running_status')
    op.add_column('users', sa.Column('forbidden_status', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'forbidden_status')
    op.add_column('bugs', sa.Column('bug_running_status', sa.BOOLEAN(), nullable=True))
    op.drop_constraint(None, 'bugs', type_='unique')
    op.drop_column('bugs', 'bug_forbidden_status')
    ### end Alembic commands ###
