"""add Regression test version

Revision ID: 105b0e27823a
Revises: 360167e4368
Create Date: 2016-03-17 11:20:12.881000

"""

# revision identifiers, used by Alembic.
revision = '105b0e27823a'
down_revision = '360167e4368'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugs', sa.Column('regression_test_version', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bugs', 'regression_test_version')
    ### end Alembic commands ###
