"""empty message

Revision ID: 11eaab5b792f
Revises: 5f785c6318ab
Create Date: 2016-07-15 10:36:31.280000

"""

# revision identifiers, used by Alembic.
revision = '11eaab5b792f'
down_revision = '5f785c6318ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
