"""empty message

Revision ID: 158e00081571
Revises: 4af4b74630ff
Create Date: 2016-07-20 10:28:53.137000

"""

# revision identifiers, used by Alembic.
revision = '158e00081571'
down_revision = '4af4b74630ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
