"""init

Revision ID: 195a370c3dda
Revises: None
Create Date: 2016-04-14 19:20:12.433000

"""

# revision identifiers, used by Alembic.
revision = '195a370c3dda'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
