"""empty message

Revision ID: 1b7a01995b9f
Revises: 1f0af1a9563d
Create Date: 2016-03-11 11:11:13.932000

"""

# revision identifiers, used by Alembic.
revision = '1b7a01995b9f'
down_revision = '1f0af1a9563d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugs', sa.Column('resolve_version', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bugs', 'resolve_version')
    ### end Alembic commands ###
