"""init 3

Revision ID: 1f0af1a9563d
Revises: 6466e3f011
Create Date: 2016-01-14 14:54:37.967000

"""

# revision identifiers, used by Alembic.
revision = '1f0af1a9563d'
down_revision = '6466e3f011'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versioninfo', sa.Column('product', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('versioninfo', 'product')
    ### end Alembic commands ###
