"""add photo2

Revision ID: 214542d35112
Revises: 22adfa118f87
Create Date: 2015-12-20 22:39:53.604000

"""

# revision identifiers, used by Alembic.
revision = '214542d35112'
down_revision = '22adfa118f87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
