"""add version_features

Revision ID: 351160a3f6c3
Revises: 1b7a01995b9f
Create Date: 2016-03-16 15:09:24.614000

"""

# revision identifiers, used by Alembic.
revision = '351160a3f6c3'
down_revision = '1b7a01995b9f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versioninfo', sa.Column('version_features', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('versioninfo', 'version_features')
    ### end Alembic commands ###
