"""add bug features

Revision ID: 360167e4368
Revises: 351160a3f6c3
Create Date: 2016-03-16 15:57:23.328000

"""

# revision identifiers, used by Alembic.
revision = '360167e4368'
down_revision = '351160a3f6c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugs', sa.Column('version_features', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bugs', 'version_features')
    ### end Alembic commands ###
