"""add productinfo table

Revision ID: 3a782cc1b1c5
Revises: 290128547a0
Create Date: 2016-01-05 21:29:29.418000

"""

# revision identifiers, used by Alembic.
revision = '3a782cc1b1c5'
down_revision = '290128547a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=64), nullable=True),
    sa.Column('product_version', sa.Text(), nullable=True),
    sa.Column('product_software', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id'),
    sa.UniqueConstraint('product_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productinfo')
    ### end Alembic commands ###
