"""add photo

Revision ID: 43a55dd9f40e
Revises: 190163627111
Create Date: 2015-12-20 22:16:00.938000

"""

# revision identifiers, used by Alembic.
revision = '43a55dd9f40e'
down_revision = '190163627111'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugs', sa.Column('bug_photos', sa.Text(), nullable=True))
    op.create_index('ix_roles_default', 'roles', ['default'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roles_default', 'roles')
    op.drop_column('bugs', 'bug_photos')
    ### end Alembic commands ###
