"""empty message

Revision ID: 441e015a7711
Revises: 158e00081571
Create Date: 2016-07-20 10:33:38.065000

"""

# revision identifiers, used by Alembic.
revision = '441e015a7711'
down_revision = '158e00081571'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugs', sa.Column('bug_insiders', sa.String(length=64), nullable=True))
    op.drop_column('bugs', 'system_view')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugs', sa.Column('system_view', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('bugs', 'bug_insiders')
    ### end Alembic commands ###
