"""init 

Revision ID: 47252b81f1d0
Revises: None
Create Date: 2016-01-14 14:50:46.173000

"""

# revision identifiers, used by Alembic.
revision = '47252b81f1d0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('versioninfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_name', sa.Text(), nullable=True),
    sa.Column('version_descrit', sa.Text(), nullable=True),
    sa.Column('software_version', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_versioninfo_create_time', 'versioninfo', ['create_time'], unique=False)
    op.create_index('ix_versioninfo_update_time', 'versioninfo', ['update_time'], unique=False)
    op.create_table('productinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=64), nullable=True),
    sa.Column('product_descrit', sa.Text(), nullable=True),
    sa.Column('product_status', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_name')
    )
    op.create_index('ix_productinfo_create_time', 'productinfo', ['create_time'], unique=False)
    op.create_index('ix_productinfo_update_time', 'productinfo', ['update_time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_productinfo_update_time', 'productinfo')
    op.drop_index('ix_productinfo_create_time', 'productinfo')
    op.drop_table('productinfo')
    op.drop_index('ix_versioninfo_update_time', 'versioninfo')
    op.drop_index('ix_versioninfo_create_time', 'versioninfo')
    op.drop_table('versioninfo')
    ### end Alembic commands ###
