"""empty message

Revision ID: 4af4b74630ff
Revises: 7e1d81dc275a
Create Date: 2016-07-20 10:25:33.339000

"""

# revision identifiers, used by Alembic.
revision = '4af4b74630ff'
down_revision = '7e1d81dc275a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
