"""empty message

Revision ID: 4f051aaebe51
Revises: f3ec0ca3a110
Create Date: 2016-07-15 11:29:36.047000

"""

# revision identifiers, used by Alembic.
revision = '4f051aaebe51'
down_revision = 'f3ec0ca3a110'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
