"""empty message

Revision ID: 5d0de6767748
Revises: None
Create Date: 2016-04-22 10:36:33.870000

"""

# revision identifiers, used by Alembic.
revision = '5d0de6767748'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bugs', ['bug_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bugs', type_='unique')
    ### end Alembic commands ###
