"""empty message

Revision ID: 5f785c6318ab
Revises: None
Create Date: 2016-07-15 10:06:29.505000

"""

# revision identifiers, used by Alembic.
revision = '5f785c6318ab'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugs', sa.Column('bug_running_status', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bugs', 'bug_running_status')
    ### end Alembic commands ###
