"""init 2

Revision ID: 6466e3f011
Revises: 47252b81f1d0
Create Date: 2016-01-14 14:53:23.100000

"""

# revision identifiers, used by Alembic.
revision = '6466e3f011'
down_revision = '47252b81f1d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
