"""empty message

Revision ID: a40d49ed74db
Revises: None
Create Date: 2016-07-29 14:38:21.098000

"""

# revision identifiers, used by Alembic.
revision = 'a40d49ed74db'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versioninfo', sa.Column('software_id', sa.Integer(), nullable=True))
    op.add_column('versioninfo', sa.Column('software_status', sa.Boolean(), nullable=True))
    op.add_column('versioninfo', sa.Column('version_features_id', sa.Integer(), nullable=True))
    op.add_column('versioninfo', sa.Column('version_features_status', sa.Boolean(), nullable=True))
    op.add_column('versioninfo', sa.Column('version_status', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_versioninfo_product'), 'versioninfo', ['product'], unique=False)
    op.drop_index('ix_versioninfo_create_time', table_name='versioninfo')
    op.drop_index('ix_versioninfo_update_time', table_name='versioninfo')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_versioninfo_update_time', 'versioninfo', ['update_time'], unique=False)
    op.create_index('ix_versioninfo_create_time', 'versioninfo', ['create_time'], unique=False)
    op.drop_index(op.f('ix_versioninfo_product'), table_name='versioninfo')
    op.drop_column('versioninfo', 'version_status')
    op.drop_column('versioninfo', 'version_features_status')
    op.drop_column('versioninfo', 'version_features_id')
    op.drop_column('versioninfo', 'software_status')
    op.drop_column('versioninfo', 'software_id')
    ### end Alembic commands ###
