"""empty message

Revision ID: aba3b91d74a8
Revises: cc9b7c1b7518
Create Date: 2016-07-18 10:59:04.213000

"""

# revision identifiers, used by Alembic.
revision = 'aba3b91d74a8'
down_revision = 'cc9b7c1b7518'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugs', sa.Column('bug_running_status', sa.Boolean(), nullable=False))
    op.drop_column('bugs', 'bug_forbidden_status')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugs', sa.Column('bug_forbidden_status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('bugs', 'bug_running_status')
    ### end Alembic commands ###
