"""empty message

Revision ID: b12f11e62aa3
Revises: 441e015a7711
Create Date: 2016-07-20 10:36:40.810000

"""

# revision identifiers, used by Alembic.
revision = 'b12f11e62aa3'
down_revision = '441e015a7711'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugs', sa.Column('bug_insiders', sa.String(length=64), nullable=True))
    op.drop_column('bugs', 'system_view')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugs', sa.Column('system_view', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('bugs', 'bug_insiders')
    ### end Alembic commands ###
