"""empty message

Revision ID: cc9b7c1b7518
Revises: 4f051aaebe51
Create Date: 2016-07-15 12:09:57.758000

"""

# revision identifiers, used by Alembic.
revision = 'cc9b7c1b7518'
down_revision = '4f051aaebe51'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugs', sa.Column('bug_forbidden_status', sa.Boolean(), nullable=False))
    op.drop_column('bugs', 'bug_running_status')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugs', sa.Column('bug_running_status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('bugs', 'bug_forbidden_status')
    ### end Alembic commands ###
