"""empty message

Revision ID: d7ded3e5945e
Revises: f153757d7bad
Create Date: 2016-07-19 15:09:39.582000

"""

# revision identifiers, used by Alembic.
revision = 'd7ded3e5945e'
down_revision = 'f153757d7bad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('forbidden_status', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'forbidden_status')
    ### end Alembic commands ###
