"""empty message

Revision ID: d7e3bf1f008a
Revises: aba3b91d74a8
Create Date: 2016-07-18 11:05:55.962000

"""

# revision identifiers, used by Alembic.
revision = 'd7e3bf1f008a'
down_revision = 'aba3b91d74a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
