"""empty message

Revision ID: e150ec6634dd
Revises: 11eaab5b792f
Create Date: 2016-07-15 10:37:31.048000

"""

# revision identifiers, used by Alembic.
revision = 'e150ec6634dd'
down_revision = '11eaab5b792f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
