"""empty message

Revision ID: f153757d7bad
Revises: d7e3bf1f008a
Create Date: 2016-07-18 11:12:50.234000

"""

# revision identifiers, used by Alembic.
revision = 'f153757d7bad'
down_revision = 'd7e3bf1f008a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugs', sa.Column('bug_forbidden_status', sa.Boolean(), nullable=False))
    op.drop_column('bugs', 'bug_running_status')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugs', sa.Column('bug_running_status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('bugs', 'bug_forbidden_status')
    ### end Alembic commands ###
