"""empty message

Revision ID: f3ec0ca3a110
Revises: 09bd3cd9189a
Create Date: 2016-07-15 11:27:59.144000

"""

# revision identifiers, used by Alembic.
revision = 'f3ec0ca3a110'
down_revision = '09bd3cd9189a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bugs', 'bug_running_status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bugs', 'bug_running_status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    ### end Alembic commands ###
