"""modify productinfo table

Revision ID: f4093872583
Revises: 3a782cc1b1c5
Create Date: 2016-01-05 22:21:16.698000

"""

# revision identifiers, used by Alembic.
revision = 'f4093872583'
down_revision = '3a782cc1b1c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productinfo',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=64), nullable=True),
    sa.Column('product_version', sa.Text(), nullable=True),
    sa.Column('product_software', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productinfo')
    ### end Alembic commands ###
